#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#=============================================================================
#  MusE
#  Linux Music Editor
#  $Id:$
#
#  Copyright (C) 2002-2023 MusE development team
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the
#  Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
#=============================================================================
import tkinter as tk
from tkinter import ttk
import sys

root = tk.Tk()
root.title('Constant length')
label = ttk.Label(text="Make all events of length:")
label.pack(fill=tk.X, padx=5, pady=5)

eventLength = ttk.Combobox(root, state = "readonly")
eventLength['values'] = ["1/1", "1/2", "1/4", "1/8", "1/16", "1/32", "1/64" ]
eventLength.pack(fill=tk.X, padx=5, pady=5)
eventLength.current(4)
def execute():
    idx = eventLength.current()
    print(f"execute {idx}")

    testFile = open(sys.argv[1],"r")
    inputEvents = testFile.readlines()
    testFile.close()

    beatDiv = 1 << idx
    print ("beatDiv=",beatDiv)
    eventLen=0
    #get beat length to calculate minimum length of event
    for line in inputEvents:
        if line.startswith('BEATLEN'):
            tag,tick = line.split(' ')
            eventLen=int(int(tick)/beatDiv * 4)
            break

    outputEvents=[]
    #loop through events
    for line in inputEvents:
        
        if line.startswith('NOTE'):
            tag,tick,note,length,velocity = line.split(' ')

            length=eventLen
            newLine=tag+" "+tick+" "+note+" "+str(length)+" "+velocity + "\n"
            outputEvents.append(newLine)
            
        else:
            outputEvents.append(line)
        
    testFile = open(sys.argv[1],"w")
    testFile.writelines(outputEvents)
    testFile.close()

    sys.exit()

execute_cb = ttk.Button(root, text="Execute", command=execute)
execute_cb.pack(fill=tk.X, padx=5, pady=5)


root.mainloop()
