#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#=============================================================================
#  MusE
#  Linux Music Editor
#  $Id:$
#
#  Copyright (C) 2002-2023 MusE development team
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the
#  Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
#=============================================================================
import tkinter as tk
from tkinter import ttk
import sys

root = tk.Tk()
root.title('Constant Velocity For Event')

label = ttk.Label(text="Note number (60 = C3):")
label.pack(fill=tk.X, padx=5, pady=5)
inputValue = ttk.Entry()
inputValue.pack(fill=tk.X, padx=5, pady=5)
inputValue.insert(0,"60")

label = ttk.Label(text="New velocity (1-127):")
label.pack(fill=tk.X, padx=5, pady=5)
inputValue2 = ttk.Entry()
inputValue2.pack(fill=tk.X, padx=5, pady=5)
inputValue2.insert(0,"100")

def execute():

    fileToProcess = open(sys.argv[1],"r")
    inputEvents = fileToProcess.readlines()
    fileToProcess.close()
    
    selectedNote = int(inputValue.get())
    newVelocity = int(inputValue2.get())
    
    outputEvents=[]

    #loop through events
    for line in inputEvents:
        if line.startswith('NOTE'):
            tag,tick,note,length,velocity = line.split(' ')
            if int(note) == int(selectedNote):
                outputEvents.append("%s %s %s %s %d\n"%(tag,tick,note,length,newVelocity))
            else:
                outputEvents.append(line)
        else:
            outputEvents.append(line)

    fileToProcess = open(sys.argv[1],"w")
    fileToProcess.writelines(outputEvents)
    fileToProcess.close()

    sys.exit()

execute_cb = ttk.Button(root, text="Execute", command=execute)
execute_cb.pack(fill=tk.X, padx=5, pady=5)


root.mainloop()
