#!/usr/bin/python
# -*- coding: utf-8 -*-
# MusE external midi processing script
# By: Mathias Gyllengahm 2009
# DoubleSpeed

import sys,time
testFile = file(sys.argv[1],"r")
inputEvents = testFile.readlines()
testFile.close()

outputEvents=[]
#loop through events
for line in inputEvents:

      if line.startswith('NOTE'):
            tag,tick,pitch,length,velocity = line.split(' ')
            newline = tag + " " + str(int(tick)/2) + " " + pitch + " " + length + " " + velocity
            outputEvents.append(newline)

testFile = file(sys.argv[1],"w")
testFile.writelines(outputEvents)
testFile.close()

