#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# MusE external midi processing script
# By: Robert Jonsson (c) 2013
# RemoveDoubles
#=============================================================================
#  MusE
#  Linux Music Editor
#  $Id:$
#
#  Copyright (C) 2002-2013 by Werner Schweer and others
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the
#  Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
#=============================================================================

import sys,time
testFile = open(sys.argv[1],"r")
inputEvents = testFile.readlines()
testFile.close()

outputEvents=[]
#loop through events and omit doubles
for line in inputEvents:
      if line.startswith('NOTE'):
            tag,tick,pitch,length,velocity = line.split(' ')
            found=False
            for outline in outputEvents:
                outtag,outtick,outpitch,outlength,outvelocity = outline.split(' ')
                if tick == outtick and pitch == outpitch and outvelocity == outvelocity:
                    found=True
                    break
            if not found:
              newline = tag + " " + str(int(tick)) + " " + pitch + " " + length + " " + velocity
              outputEvents.append(newline)

testFile = open(sys.argv[1],"w")
testFile.writelines(outputEvents)
testFile.close()

