//=============================================================================
//  MusE
//  Linux Music Editor
//
//  Hand-written, stable header - NOT generated by cmake, NOT touched by
//  reconfigures. Declares the accessor for the git describe string; the
//  string itself is resolved at build time in the generated git_version.cpp
//  (see git_version.cpp.in), so that including this header never forces a
//  recompile. Only git_version.cpp itself (tiny, cheap) is rebuilt when the
//  working tree's git-describe state changes, and the final binary is
//  simply relinked.
//=============================================================================

#ifndef _MUSE_GIT_VERSION_H_
#define _MUSE_GIT_VERSION_H_

// Returns "<branch> | <describe> | <date>", or an empty string if the
// build wasn't made from a git checkout (e.g. tarball release).
const char* museGitVersionString();

#endif // _MUSE_GIT_VERSION_H_
