name: Create AppImage for release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        default: '4.2.1'
        required: true
#on: push
#  push:
#    tags:
#    - 'muse_*'
#    - '!muse_*_pre*'

env: 
  BUILD_TYPE: Release
  TAG: ${{ github.event.inputs.tag }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ env.TAG }}
                  
    - name: Install Deps
      run: |
        sudo apt-get update
        # See PR 1077. Required to find libatomic for some archs.
        sudo apt-get install -y cmake extra-cmake-modules
        sudo apt-get install -y libsndfile1-dev libsamplerate0-dev \
          libjack-jackd2-dev ladspa-sdk liblo-dev dssi-dev \
          libfluidsynth-dev libgtkmm-2.4-dev \
          libinstpatch-dev librubberband-dev python3-dev librtaudio-dev liblrdf0-dev
        sudo apt-get install -y qtbase5-dev qttools5-dev qttools5-dev-tools libqt5svg5-dev
        sudo apt-get install -y mesa-common-dev libglu1-mesa-dev
        
        # libfuse2 is required on newer Ubuntu runners to execute AppImages inside the container
        sudo apt-get install -y fuse libfuse2
        
        sudo apt-get install -y lv2-dev libserd-dev libsord-dev libsratom-dev liblilv-dev

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      run: |
        REPO_PATH=$GITHUB_WORKSPACE/src     
        cmake $REPO_PATH -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX=/usr -DMODULES_BUILD_STATIC=ON
        
    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: 
        cmake --build . --config $BUILD_TYPE -j3
        
    - name: Create AppImage
      working-directory: ${{runner.workspace}}/build
      run: |
        make -j3 DESTDIR=appdir install ; find appdir/
        
        find appdir \( -name "moc_*" -or -name "*.o" -or -name "qrc_*" -or -name "Makefile*" -or -name "*.a" \) -exec rm {} \;
        wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
        wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
        wget -c "https://raw.githubusercontent.com/linuxdeploy/linuxdeploy-plugin-gtk/master/linuxdeploy-plugin-gtk.sh"
        wget https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/releases/download/continuous/linuxdeploy-plugin-appimage-x86_64.AppImage
        chmod +x linuxdeploy*.AppImage linuxdeploy-plugin-gtk.sh
        
        export MUSEDIR=$(basename -a ${{runner.workspace}}/build/appdir/usr/lib/muse-*)      
        LIB_MODULES=${{runner.workspace}}/build/appdir/usr/lib/$MUSEDIR/modules
        LIB_PLUGINS=${{runner.workspace}}/build/appdir/usr/lib/$MUSEDIR/plugins
        LIB_SYNTHI=${{runner.workspace}}/build/appdir/usr/lib/$MUSEDIR/synthi
        LIB_CONV=${{runner.workspace}}/build/appdir/usr/lib/$MUSEDIR/converters
        export LD_LIBRARY_PATH=$LIB_MODULES:$LIB_PLUGINS:$LIB_SYNTHI:$LIB_CONV:$LD_LIBRARY_PATH
        
        # install GTK library dependencies for LV2 uis
        sudo apt-get install -y patchelf libgtk2.0-dev libglib2.0-dev librsvg2-dev

        export DEPLOY_GTK_VERSION=2
        ./linuxdeploy-x86_64.AppImage --appdir appdir --plugin=gtk
        
        # install QT library dependencies for MusE
        ./linuxdeploy-x86_64.AppImage --appdir appdir --plugin=qt
        
        echo '#! /usr/bin/env bash' > appdir/AppRun
        echo 'set -e' >> appdir/AppRun
        echo 'this_dir=$(readlink -f $(dirname "$0"))' >> appdir/AppRun
        echo 'export LD_LIBRARY_PATH="$this_dir"/usr/lib:$LD_LIBRARY_PATH' >> appdir/AppRun
        echo 'exec "$this_dir"/AppRun.wrapped "$@"' >> appdir/AppRun
        
        export VERSION=${{ env.TAG }}
        ./linuxdeploy-plugin-appimage-x86_64.AppImage --appdir appdir 
    
    - name: Upload AppImage  
      uses: actions/upload-artifact@v4
      with:
        name: AppImage-release-${{ env.TAG }}
        path: ${{runner.workspace}}/build/MusE-*-x86_64.AppImage
