name: Compatibility build

on: 
  push:
    branches:
      - master
env: 
  BUILD_TYPE: Release

jobs:
  compat:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
                  
    - name: Install Deps
      run: |
        sudo apt-get update

        # See PR 1077. Required to find libatomic for some archs.
        sudo apt-get install -y libsndfile1-dev libsamplerate0-dev \
          libjack-jackd2-dev ladspa-sdk liblo-dev dssi-dev \
          libfluidsynth-dev libgtkmm-2.4-dev \
          libinstpatch-dev librubberband-dev python3-dev librtaudio-dev \
          liblilv-dev lv2-dev liblrdf0-dev cmake extra-cmake-modules
                
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.9.5'

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      run: |
        REPO_PATH=$GITHUB_WORKSPACE/src  
        cmake $REPO_PATH -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_SHARED_LINKER_FLAGS=-Wl,--no-undefined -DMODULES_BUILD_STATIC=ON
        
    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: 
        cmake --build . --config $BUILD_TYPE -j3
